Doc/plano custos
fga-eps-mds/2022-2-Alectrion-DOC pull request #23
Opened 2022-11-30 14:22 UTC by AlineLermen

## Modificações
* altera _sidebar para acrescentar documento EAP e plano de custos
* cria documento de plano de custos

## _Issue_ relacionado
Resolve #22 

## Motivação e Contexto
Essa modificação é necessária para documentar nossa estimativa de custos e orçamento.

## Como foi testado?
Foi testado localmente utilizando o comando `docsify serve`

## Tipo de modificações
- [x] Novo documento

## Lista de controle:
- [x] Meu código segue a folha de estilos implementada
- [x] Meu _commits_ segue a política de commits do repo.
- [x] Atualizei a Documentação

2022-11-30 19:08 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +
Sugestão:

"Para consolidação dos custos, utilizamos a planilha conforme a Tabela 1 abaixo"
E ai colocar "Tabela 1: título", centralizado.

2022-11-30 19:10 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +> [1] Escritório de Projetos. Disponível em: https://escritoriodeprojetos.com.br/gerenciamento-dos-custos-do-projeto. Acesso em: 30 de novembro de 2022
Sugestão: toda referência se iniciar com o autor, depois título do conteúdo.
Ex.:
[2] Neoenergia Brasília. Tarifas. Disponível em: https://www.neoenergiabrasilia.com.br/residencial-e-rural/Paginas/tarifas.aspx. Acesso em: 30 de novembro de 2022

2022-12-06 13:39 UTC, ErickGiffoni requested changes
Antes de aprovar:

- Retirar a pasta Documentos de dentro da "Documentation". Essa "Documentation" não é necessária, conforme o Samuel me explicou. Inclusive, no PR #21 foi feita essa reestruturação. De boa ?

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/documentos.md
> +- [EAP](./documentation/Documentos/eap.md)
```suggestion
# Documentos

A seguinte documentação faz parte do projeto Alectrion:

- [EAP](./Documentos/eap.md)
```

A referência ```- [Plano de custos](./Planejamento/custos.md)``` pro Plano de custos entraria no Planejamento/planejamento.md lá no meu PR #21 .

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/_sidebar.md
>  * [Home](../README.md)
A sidebar ficará assim, com a não necessidade da pasta "documentation":
(Exemplo)
```
* [Home](../README.md)
* [Planejamento](./Planejamento/planejamento.md)
   - [Plano de Comunicação](./Planejamento/comunicacao.md)
   - [Plano de custos](./documentation/Documentos/custos.md)
* [Documentos](./Documentos/)
  - [EAP](./documentation/Documentos/eap.md)
* [Semanas](./Semanas/semanas.md)
* [Sprint](./Sprint/sprints.md)
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +### Recursos humanos
```suggestion
### 2.1 Recursos humanos
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +### Equipamentos
```suggestion
### 2.2 Equipamentos
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +### Ferramentas
```suggestion
### 2.3 Ferramentas
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +### Capacitação
```suggestion
### 2.4 Capacitação
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +### Infraestrutura
```suggestion
### 2.5 Infraestrutura
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +#### Internet
```suggestion
#### 2.5.1 Internet
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +#### Energia
```suggestion
#### 2.5.2 Energia
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +#### Custo TOTAL infraestrutura
```suggestion
#### 2.5.3 Custo TOTAL infraestrutura
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +
```suggestion

<figcaption align='center'>
   Planilha 1: Custos do projeto Alectrion
   <br>
</figcaption>

```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +Para consolidação dos custos, utilizamos a planilha conforme abaixo.
```suggestion
Para consolidação dos custos, utilizamos a Planilha 1 conforme abaixo.
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +|04/12/2022| Adiciona custo de recursos humanos e ajusta referências | Aline Lermen |
```suggestion
|04/12/2022| Adiciona custo de recursos humanos e ajusta referências | Aline Lermen |
|06/12/2022| Revisão do documento e pequenas correções | Aline Lermen, Erick Giffoni |
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +Para essa estimativa de custos foi utilizado o custo médio anual por aluno de instituto federal. De acordo com [jornal da unesp](https://jornal.unesp.br/2022/06/08/cobranca-de-mensalidade-nao-e-a-sol
```suggestion
Para essa estimativa de custos foi utilizado o custo médio anual por aluno de instituto federal. De acordo com [jornal da unesp](https://jornal.unesp.br/2022/06/08/cobranca-de-mensalidade-nao-e-a-solucao-para-o-financiamento-da-universidade-publica/) [5], esse custo é de R$27.850 anual por aluno. Considerando as 16 semanas de projeto e os 13 integrantes da equipe, temos os seguintes cálculos.
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +Para a capacitação dos integrantes do grupo não foi utilizado nenhum meio pago, como cursos por exemplo.
Será que não vale a pena mencionar aquele curso da Udemy que alguns compraram ?
Se não corre o risco do professor perguntar: "tá, se não teve meio pago, como vcs capacitaram os MDS ?"

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +Para cálculo do custo de internet utilizaremos o preço médio de planos de 250mb/M, que de acordo com [melhorescolha](https://melhorescolha.com/internet-banda-larga/brasilia-df/) é cerca de R$ 89,99 m
Se for 250 mega bytes, então fica:
```suggestion
Para cálculo do custo de internet utilizaremos o preço médio de planos de 250 MB por mês que, de acordo com [melhorescolha](https://melhorescolha.com/internet-banda-larga/brasilia-df/) [4],é cerca de R$ 89,99.
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +Para a estimativa de energia, seguiu-se os dados da [tabela de tarifas](https://www.neoenergiabrasilia.com.br/residencial-e-rural/Documents/tafiras%20vigentes/01_nbsb_tarifas_energia_eletrica_grupoB_
```suggestion
Para a estimativa de energia, seguiu-se os dados da [tabela de tarifas](https://www.neoenergiabrasilia.com.br/residencial-e-rural/Documents/tafiras%20vigentes/01_nbsb_tarifas_energia_eletrica_grupoB_nov_2022_reh3134.pdf) [2] da [neoenergiabrasilia](https://www.neoenergiabrasilia.com.br/Paginas/default.aspx), com os dados vigentes de novembro de 2022 à outubro de 2023. Segundo essa tabela, o custo do KW/h residencial, consumo ativo, de Brasília é cerca de R$0,70.
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +Segundo dados de 2021 da [cultura uol](https://cultura.uol.com.br/noticias/26097_6-maneiras-de-economizar-na-conta-de-luz-do-home-office.html), um notebook consome em média cerca de 65W/h, conectado
```suggestion
Segundo dados de 2021 da [cultura uol](https://cultura.uol.com.br/noticias/26097_6-maneiras-de-economizar-na-conta-de-luz-do-home-office.html) [3], um notebook consome em média cerca de 65W/h, conectado ao carregador. Consideramos que cada integrante da equipe trabalhará 4 horas por semana em sua residência, ao longo de 16 semanas. Utilizando esses dados para cálculo, temos:
```

2022-12-06 13:39 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +Considerando as estimativas de custos acima calculadas, o orçamento total para o projeto seria de
```suggestion
Considerando as estimativas de custos acima calculadas, o orçamento total para o projeto é:
```

2022-12-08 17:28 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +
Lembrar disso

2022-12-08 17:29 UTC, ErickGiffoni commented
Quando eu puder revisar novamente me avisa

2022-12-08 17:42 UTC, ErickGiffoni commented on docs/documentation/Documentos/custos.md
> +|04/12/2022| Adiciona custo de recursos humanos e ajusta referências | Aline Lermen |
Lembrar

2022-12-08 17:55 UTC, AlineLermen commented
> Quando eu puder revisar novamente me avisa

Pode revisar por favor

2022-12-08 18:19 UTC, AlvaroLeles approved these changes

2022-12-08 19:21 UTC, ErickGiffoni requested changes
Falta pouco pra marcar o gol

2022-12-08 19:21 UTC, ErickGiffoni commented on docs/Planejamento/custos.md
> +27,90 x 13 = R$**195,30**
Hmmmm, saquei... eu colocaria somente a quantidade de pessoas que compraram mesmo... se não me engano foram 3

2022-12-08 19:21 UTC, ErickGiffoni commented on docs/Planejamento/custos.md
> +|04/12/2022| Adiciona custo de recursos humanos e ajusta referências | Aline Lermen |
```suggestion
|04/12/2022| Adiciona custo de recursos humanos e ajusta referências | Aline Lermen |
|06/12/2022| Revisão do documento e pequenas correções | Aline Lermen, Erick Giffoni |
```

2022-12-08 19:26 UTC, AlineLermen commented on docs/Planejamento/custos.md
> +27,90 x 13 = R$**195,30**
Isso, fiz o cálculo com 7 integrantes, só confundi na hora de anotar aí

2022-12-08 19:35 UTC, ErickGiffoni approved these changes

2022-12-09 18:53 UTC, merged