Atualização do README: repo DOC
fga-eps-mds/2022-2-Alectrion-DOC pull request #39
Opened 2022-12-06 15:17 UTC by ErickGiffoni

## Modificações

Muda um pouco alguns textos e adiciona os integrantes desse semestre

## _Issue_ relacionado

Resolve parcialmente #38

## Motivação e Contexto

Modificação necessária para atender ao contexto das diretivas do projeto para o semestre de 2022-2.

## Como foi testado?

- Testado com o preview do VsCode
- Testado com docsify serve

## Tipo de modificações

- Atualização de documentação

## Lista de controle:
- [x] Meu código segue a folha de estilos implementada
- [x] Meu _commits_ segue a política de commits do repo.
- [x] Atualizei a Documentação

2022-12-06 15:20 UTC, ErickGiffoni commented
Acho que vale a pena esperar o PR #21 ser aprovado e "merjado" antes de revisar este aqui, porque criei esta branch a partir da branch do PR 21.

2022-12-08 17:31 UTC, ErickGiffoni commented
Favor revisar os outros PR relacionados também:
- https://github.com/fga-eps-mds/2022-2-Alectrion-EquipamentApi/pull/1
- https://github.com/fga-eps-mds/2022-2-Alectrion-FrontEnd/pull/1
- https://github.com/fga-eps-mds/2022-2-Alectrion-UserAPI/pull/1
- https://github.com/fga-eps-mds/2022-2-Alectrion-Gateway/pull/1

2022-12-08 23:23 UTC, SamButers requested changes

2022-12-08 23:23 UTC, SamButers commented on README.md
> +feito para atender às demanadas da DSTI (Divisão de Suporte Técnico Interno) da Polícia Civil do estado de Goiás.
Demanadas.
Erro ortográfico.

2022-12-08 23:23 UTC, SamButers commented on docs/README.md
> +feito para atender às demanadas da DSTI (Divisão de Suporte Técnico Interno) da Polícia Civil do estado de Goiás.
Demanadas.
Erro ortográfico.

2022-12-08 23:23 UTC, SamButers commented on docs/_sidebar.md
> +* [Home](./README.md)
Use somente /, não ./README.md.

2022-12-08 23:26 UTC, SamButers commented
Erros ortográficos presentes nos demais READMEs.

2022-12-09 13:59 UTC, ErickGiffoni commented on README.md
> +feito para atender às demanadas da DSTI (Divisão de Suporte Técnico Interno) da Polícia Civil do estado de Goiás.
```suggestion
feito para atender às demandas da DSTI (Divisão de Suporte Técnico Interno) da Polícia Civil do estado de Goiás.
```

2022-12-09 13:59 UTC, ErickGiffoni commented on docs/README.md
> +feito para atender às demanadas da DSTI (Divisão de Suporte Técnico Interno) da Polícia Civil do estado de Goiás.
```suggestion
feito para atender às demandas da DSTI (Divisão de Suporte Técnico Interno) da Polícia Civil do estado de Goiás.
```

2022-12-09 14:00 UTC, ErickGiffoni commented on docs/_sidebar.md
> +* [Home](./README.md)
```suggestion
* [Home](/README.md)
```

2022-12-09 14:16 UTC, SamButers requested changes

2022-12-09 14:16 UTC, SamButers commented on docs/_sidebar.md
> +* [Home](/README.md)
Quis dizer usar somente ``[Home](/)``, não sem o ponto. 😜

2022-12-09 14:22 UTC, SamButers commented on docs/_sidebar.md
> +* [Home](/README.md)
```suggestion
* [Home](/)
```

2022-12-09 14:27 UTC, SamButers approved these changes

2022-12-10 21:20 UTC, RuanMoura requested changes

2022-12-10 21:20 UTC, RuanMoura commented on README.md
> + - Docker-compose
```suggestion
```

2022-12-10 21:20 UTC, RuanMoura commented on docs/README.md
> + - Docker-compose
```suggestion
```

2022-12-10 21:23 UTC, RuanMoura approved these changes
Looks good to me! Nice work!

2022-12-10 21:25 UTC, merged