Doc/plano de riscos
fga-eps-mds/2022-2-Alectrion-DOC pull request #43
Opened 2022-12-10 01:51 UTC by JoaoVitorFarias

## Modificações

- Atualização da imagem da EAP
- Adição do plano de gerenciamento de riscos na sidebar
- Ajuste no template de documentação
- 
## Descrição

Criação do plano de gerenciamento de riscos e atualização da EAP.

## _Issue_ relacionado

Resolve:
- #25 
- #27 

## Tipo de modificações

- [X] Novo documento
- [X] Ajuste em documentos

## Lista de controle:
- [X] Meu _commits_ segue a política de commits do repo.
- [X] Atualizei a Documentação

2022-12-10 14:18 UTC, ErickGiffoni commented
@JoaoVitorFarias lembra de resolver os conflitos

2022-12-10 17:36 UTC, AlineLermen requested changes
Na imagem da EAP, na parte de qualidade -> monitoramento, está escrito `SnarCloud` ao invés de `SonarCloud`

2022-12-10 21:11 UTC, ErickGiffoni approved these changes

2022-12-11 14:10 UTC, AlineLermen approved these changes

2022-12-11 15:12 UTC, merged