#29 doc: adiciona tap
fga-eps-mds/2022-2-Alectrion-DOC pull request #44
Opened 2022-12-10 02:53 UTC by JoaoVitorFarias

## Modificações

- Adição do tap na sidebar

## Descrição

Criação do termo de abertura do projeto

## _Issue_ relacionado

Resolve:
- #29 

## Tipo de modificações

- [X] Novo documento
- [X] Ajuste em documentos

## Lista de controle:
- [X] Meu _commits_ segue a política de commits do repo.
- [X] Atualizei a Documentação

2022-12-10 16:14 UTC, ErickGiffoni commented
@JoaoVitorFarias lembra de corrigir os conflitos

2022-12-10 16:19 UTC, ErickGiffoni requested changes

2022-12-10 16:19 UTC, ErickGiffoni commented on docs/Documentos/tap.md
> +O SGPI se trata de uma aplicação web feita para suprir a necessidade de gestão e consulta dos patrimônios de unidades da PCGO (Polícia Civil de Goiás), em especial para os patrimônios do setor de inf
Substituir pela descrição do que é o Alectrion, não o SGPI

2022-12-10 16:19 UTC, ErickGiffoni commented on docs/Documentos/tap.md
> +O propósito do Alectrion é oferecer uma aplicação com funcionalidades de gerenciamento de patrimônio para as delegacias da polícia civil de Goiás. Com um certo foco no setor de informática, já que no
Onde tem 
- "patrimônio" --> substituir por "equipamentos de informática"
- "setor de informática" --> "DSTI (Divisão de Suporte Técnico Interno)"

2022-12-10 16:19 UTC, ErickGiffoni commented on docs/Documentos/tap.md
> +A estimativa de custos se trata de um estudo que visa viabilizar operacional e financeiramente a execução de um projeto. Sua aplicação deve ser efetiva e condizente com a realidade de ambas as partes
Fazer o link com o documento de custos que fizemos

2022-12-10 16:19 UTC, ErickGiffoni commented on docs/Documentos/tap.md
> +|09/12/2022| Criação do documento | João Vitor |
Assim que fizer os ajustes:

```suggestion
|09/12/2022| Criação do documento | João Vitor |
|10/12/2022| Ajustes e correções | João Vitor, Erick Giffoni |
```

2022-12-11 23:03 UTC, ErickGiffoni approved these changes

2022-12-12 00:50 UTC, SamButers approved these changes

2022-12-12 00:50 UTC, merged