Adiciona a política de branches
fga-eps-mds/2022-2-Alectrion-DOC pull request #47
Opened 2022-12-10 16:02 UTC by ErickGiffoni

## Modificações

Novo documento: política de branches
Atualiza a sidebar
Adiciona imagem da política

## _Issue_ relacionado

Resolve #30 

## Como foi testado?

Com docsify localmente.

## Tipo de modificações

- [ ] Novo documento
- [ ] Nova imagem
- [ ] Complementa a sidebar

## Lista de controle:

- [ ] Meu código segue a folha de estilos implementada
- [ ] Meu _commits_ segue a política de commits do repo.
- [ ] Minhas modificações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação

2022-12-11 00:57 UTC, JoaoVitorFarias requested changes

2022-12-11 00:57 UTC, JoaoVitorFarias commented on docs/Documentos/politicas-branch.md
> +_Brnaches_ para correções urgentes de _bugs_ são criadas a partir da _branch_ **main** e são juntadas diretamente nela (por meio de um _pull request_).<br>
```suggestion
_Branches_ para correções urgentes de _bugs_ são criadas a partir da _branch_ **main** e são juntadas diretamente nela (por meio de um _pull request_).<br>
```

2022-12-12 00:00 UTC, JoaoVitorFarias approved these changes

2022-12-12 00:48 UTC, SamButers approved these changes

2022-12-12 00:48 UTC, merged