Adicionando política de pull requests
fga-eps-mds/2022-2-Alectrion-DOC pull request #74
Opened 2022-12-16 19:36 UTC by AlvaroLeles

## Modificações
Adicionando política de pull requests
## Descrição
Descrevendo uso de _labels_;
Indicando como se deve abrir e descrever _pull requests_;
Indicando como se indicar quem revisa _pull request_
## _Issue_ relacionado
Resolve #64 
## Como foi testado?
Testado localmente com ```docsify serve```
## Tipo de modificações
- [x] Alteração de documento

## Lista de controle:
- [x] Meus _commits_ seguem a política de commits do repo.
- [x] Atualizei a Documentação

2022-12-16 21:18 UTC, AlineLermen commented on docs/Documentos/politicas-branch.md
> + - **enhancement:** Label para associar a _issues_ de novas _features_;
Aqui seria issues de melhoria, certo?
```suggestion
 - **enhancement:** Label para associar a _issues_ de melhorias;
```

2022-12-16 21:19 UTC, AlineLermen commented on docs/Documentos/politicas-branch.md
> + - **MDS:** Label para associar a _issues_ que devem/podem ser realizadas por alunos da disciplina de EPS;
```suggestion
 - **MDS:** Label para associar a _issues_ que devem/podem ser realizadas por alunos da disciplina de MDS;
```

2022-12-16 21:23 UTC, AlineLermen commented on docs/Documentos/politicas-branch.md
> +Sempre que implementar alterações sugeridas, deve-se avisar aos revisores para que eles dêem uma nova olhada. Ao fim, se a contribuição for aceita, o _pull request_ será _mergeado_ a branch principal
```suggestion
Sempre que implementar alterações sugeridas, deve-se avisar aos revisores para que eles dêem uma nova olhada. Ao fim, se a contribuição for aceita, o _pull request_ será _mergeado_ à branch de destino do repositório.
```

2022-12-16 21:25 UTC, AlineLermen commented on docs/Documentos/politicas-branch.md
> +Após ter resolvido uma issue e estiver satisfeito com o que foi alterado nos arquivos locais, deve-se enviar essas alterações para o repositório no GitHub por meio de commits. Após isso, pode-se ir p
```suggestion
Após ter resolvido uma issue e estar satisfeito com o que foi alterado nos arquivos locais, deve-se enviar essas alterações para o repositório no GitHub por meio de commits. Após isso, pode-se ir para o repositório e abrir um _pull request_, onde deve-se escolher a _branch_ que se quer propor as alterações e informar o máximo de detalhes da contribuição, seguindo o [template de _pull requests_](https://github.com/fga-eps-mds/2022-2-Alectrion-DOC/blob/main/.github/pull_request_template.md), criando então um _pull request_ para ser revisado.
```

2022-12-16 22:48 UTC, ErickGiffoni requested changes

2022-12-16 22:48 UTC, ErickGiffoni commented on docs/Documentos/politicas-branch.md
> +Ao abrir o _pull request_ deve-se marcar ao menos dois integrantes de EPS para revisar as alterações sugeridas para, caso necessário, ser solicitado a fazer edições ou melhorias.
```suggestion
Ao abrir o _pull request_ deve-se marcar ao menos dois integrantes de EPS e dois de MDS para revisarem o conteúdo do PR. Caso seja necessário, o autor do PR será solicitado pelos revisores para fazer edições ou melhorias.
```

2022-12-16 22:48 UTC, ErickGiffoni commented on docs/Documentos/politicas-branch.md
> +|16/12/2022| Adição da política de _pull requests_ | Álvaro Leles |
```suggestion
|16/12/2022| Adição da política de _pull requests_ | Álvaro Leles |
|16/12/2022| Revisão da política de _pull requests_ | Aline Helena, Erick Giffoni |
```

2022-12-16 22:50 UTC, ErickGiffoni commented on docs/Documentos/politicas-branch.md
> + - **enhancement:** Label para associar a _issues_ de novas _features_;
De acordo

2022-12-16 22:50 UTC, ErickGiffoni commented on docs/Documentos/politicas-branch.md
> + - **MDS:** Label para associar a _issues_ que devem/podem ser realizadas por alunos da disciplina de EPS;
De acordo

2022-12-16 22:51 UTC, ErickGiffoni commented on docs/Documentos/politicas-branch.md
> +Sempre que implementar alterações sugeridas, deve-se avisar aos revisores para que eles dêem uma nova olhada. Ao fim, se a contribuição for aceita, o _pull request_ será _mergeado_ a branch principal
De acordo

2022-12-16 22:51 UTC, ErickGiffoni commented on docs/Documentos/politicas-branch.md
> +Após ter resolvido uma issue e estiver satisfeito com o que foi alterado nos arquivos locais, deve-se enviar essas alterações para o repositório no GitHub por meio de commits. Após isso, pode-se ir p
De acordo

2022-12-18 20:06 UTC, AlvaroLeles commented on docs/Documentos/politicas-branch.md
> + - **enhancement:** Label para associar a _issues_ de novas _features_;
De acordo com a descrição da label [aqui](https://github.com/fga-eps-mds/2022-2-Alectrion-DOC/labels), diz que é uma nova feature, mas se acharem que deve ser trocado para melhoria mesmo, posso trocar.

2022-12-18 20:18 UTC, AlvaroLeles commented
@AlineLermen @ErickGiffoni algumas das sugestões aplicadas

2022-12-18 22:08 UTC, AlineLermen approved these changes

2022-12-19 17:01 UTC, ErickGiffoni approved these changes

2022-12-19 17:01 UTC, merged