Guia de estilo
fga-eps-mds/2022-2-Alectrion-DOC pull request #75
Opened 2022-12-17 00:01 UTC by SamButers

## Modificações
Adição do documento de guia de estilo.
## Descrição
Adição do documento de guia de estilo e seus arquivos associados.
## _Issue_ relacionado
#60 
## Motivação e Contexto
O guia de estilo é um documento essencial e obrigatório do projeto.
## Como foi testado?
Localmente.
## Tipo de modificações
- [x] Novo documento

## Lista de controle:
- [x] Meu código segue a folha de estilos implementada
- [x] Meu _commits_ segue a política de commits do repo.
- [x] Atualizei a Documentação

2022-12-17 01:24 UTC, JoaoVitorFarias requested changes

2022-12-17 01:24 UTC, JoaoVitorFarias commented on docs/Documentos/guia-de-estilo.md
> +Os ícones usados na aplicação são os icones da biblioteca [material-icons](https://mui.com/pt/material-ui/material-icons/)
```suggestion
Os ícones usados na aplicação são os ícones da biblioteca [material-icons](https://mui.com/pt/material-ui/material-icons/)
```

2022-12-19 00:57 UTC, JoaoVitorFarias approved these changes

2022-12-19 17:11 UTC, ErickGiffoni approved these changes

2022-12-19 17:12 UTC, merged