Doc/correcao riscos
fga-eps-mds/2022-2-Alectrion-DOC pull request #78
Opened 2022-12-19 02:22 UTC by JoaoVitorFarias

## Modificações
* Correção do plano de gerenciamento de riscos
 
## Descrição
Foi realizadas as correções no plano de gerenciamento de riscos.

## _Issue_ relacionado
#67 

## Lista de controle:
- [X] Meu _commits_ segue a política de commits do repo.
- [X] Atualizei a Documentação

2022-12-19 17:20 UTC, ErickGiffoni requested changes

2022-12-19 17:20 UTC, ErickGiffoni commented on docs/Planejamento/riscos.md
> +# 4. Planejamento de resposta dos riscos
Gostei da descrição das estratégias de resposta aos riscos. Creio que só isso seja insuficiente, entretanto.

Quando o prof perguntou sobre essa parte de plano de resposta aos riscos, e até onde eu entendo sobre o assunto, responder ao risco vai além de entender as diferentes estratégias. O que podemos melhorar é mostrar, para cada risco do projeto, qual a estratégia de resposta e qual/quais o(s) passo(s) que seguiremos para responder ao risco, na eventualidade dele acontecer.

Isso poderia ser feito em uma tabela, por exemplo.

2022-12-19 18:27 UTC, RuanMoura approved these changes
Bom trabalho!

2022-12-20 16:53 UTC, AlineLermen commented on docs/Planejamento/riscos.md
> +# 4. Planejamento de resposta dos riscos
Concordo.
Acredito que para cada risco do projeto deve haver uma resposta reativa, uma resposta caso o risco realmente aconteça.

2023-01-03 11:23 UTC, AlvaroLeles approved these changes

2023-01-03 21:25 UTC, ErickGiffoni approved these changes

2023-01-03 21:25 UTC, ErickGiffoni commented
Muito bom trabalho

2023-01-03 21:25 UTC, merged