Doc/sprint
fga-eps-mds/2022-2-Alectrion-DOC pull request #79
Opened 2022-12-19 03:16 UTC by AlineLermen

## Modificações
* Modifica documento da sprint 1
* Cria documento da sprint 2

## _Issue_ relacionado
Resolve #70 

## Como foi testado?
Testado localmente com `docsify serve`

## Tipo de modificações
- [x] Alteração de documento
- [x] Novo documento

## Lista de controle:
- [x] Meu _commits_ segue a política de commits do repo.

2022-12-19 17:29 UTC, ErickGiffoni commented on docs/Sprint/sprint-1.md
> +| MDS | Yago Amin Santos | Presente |Presente |- |
Pela última coluna, ninguém esteve na _review_ ... ficou parecendo que não teve _review_... acho bom colocar um parágrafo explicando que a _review_ foi a apresentação da _release_, ou que não teve por causa disso...

2022-12-19 17:32 UTC, ErickGiffoni requested changes

2022-12-19 17:32 UTC, ErickGiffoni commented on docs/Sprint/sprint-2.md
> +| MDS | Yago Amin Santos | Presente | Ausente |- |
Como ainda não teve a _review_ dessa _sprint_ (porque a revisão é hoje), só lembrar de atualizar a lista

2022-12-19 22:20 UTC, AlineLermen commented
@ErickGiffoni Na verdade eu penso em não colocar a presença nas _reviews_, porque nós fomos pelo horário também que o cliente podia. Assim, sempre as mesmas pessoas estariam ausentes na _review_...

Na _planning_ e retrospectiva acredito ser ok manter a preesença por ser em horários que, no geral, foram marcados quando quase todos podem

Sendo assim, acha melhor retirar a coluna "_review_"?

2022-12-20 13:22 UTC, ErickGiffoni commented
> @ErickGiffoni Na verdade eu penso em não colocar a presença nas _reviews_, porque nós fomos pelo horário também que o cliente podia. Assim, sempre as mesmas pessoas estariam ausentes na _review_...
> 
> Na _planning_ e retrospectiva acredito ser ok manter a preesença por ser em horários que, no geral, foram marcados quando quase todos podem
> 
> Sendo assim, acha melhor retirar a coluna "_review_"?

Oi, Aline, leu minha mente haha
Melhor retirar a coluna da revisão
@AlineLermen

2022-12-20 16:59 UTC, ErickGiffoni approved these changes

2022-12-20 19:26 UTC, RuanMoura approved these changes
Bom trabalho!

2022-12-20 19:59 UTC, JoaoVitorFarias approved these changes

2022-12-20 19:59 UTC, merged