Atualização do plano de custos
fga-eps-mds/2022-2-Alectrion-DOC pull request #89
Opened 2022-12-20 18:58 UTC by AlineLermen

## Modificações
Atualização dos valores de recursos humanos e equipamentos, consequentemente alteração do valor total.
Planilha alterada também

## _Issue_ relacionado
Resolve #66 

## Como foi testado?
Testado localmente com `docsify serve`

## Tipo de modificações
- [x] Atualização de documento

## Lista de controle:
- [x] Meu _commits_ segue a política de commits do repo.

2022-12-21 17:55 UTC, AlvaroLeles requested changes

2022-12-21 17:55 UTC, AlvaroLeles commented on docs/Planejamento/custos.md
> +Considerando as estimativas de custos acima calculadas e uma margem de 10%, o orçamento total para o projeto em 16 meses é:
```suggestion
Considerando as estimativas de custos acima calculadas e uma margem de 10%, o orçamento total para o projeto em 16 semanas é:
```

2022-12-21 19:02 UTC, RuanMoura requested changes

2022-12-21 19:02 UTC, RuanMoura commented on docs/Planejamento/custos.md
> +* 2045,00 x 16 = R$**32.720**
Bom dia, Aline! Dei uma lida nos seus cálculos e cheguei a valores diferentes, talvez por você ter dividido o valor anual por 52, acredito que no período de férias o gasto seja menor que em período letivo, e também vejo que você considerou 5 matérias por semestre, o que não ocorre na maioria das vezes.
Sugiro usar o preço por crédito, que seria o custo anual do aluno multiplicado pela quantidade de anos padrão do curso e dividido pela quantidade de créditos necessários para formação do aluno:
Preço por crédito: 40.900 * 5 / 232
Como tanto EPS e MDS são matérias de 4 créditos o custo de cada aluno na matérias seria de:
Preço aluno na matéria: Preço por crédito * 4
E agora multiplicando pela quantidade de membros da equipe:
Preço aluno na matéria * 13
Com isso cheguei ao seguinte resultado para o custo total da equipe:
R$ 45.836,21
Você também pode pegar esse valor e dividir por 16 para obter o preço por semana da equipe.

2022-12-21 19:02 UTC, RuanMoura commented on docs/Planejamento/custos.md
> +* 157,31 x 13 = R$**2045,00**
Por que somente a disciplina de EPS ?

2023-01-03 11:17 UTC, AlvaroLeles approved these changes

2023-01-04 01:00 UTC, RuanMoura approved these changes
Bom trabalho, ficou show!!!

2023-01-04 01:00 UTC, merged